
import './globals.css'
import { Inter } from 'next/font/google'
import Navbaar from './navbaar/navbaar'
import Footer from './footer/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbaar/>
        {children}
        <Footer/>
        </body>
    
    </html>
  )
}
